name: Generate documentation
on:
  push:
    branches:
    - master
<<<<<<< HEAD
jobs:
  generate_documentation:
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: $HOME/SpacemanDMM
          key: ${{ runner.os }}-spacemandmm
=======
permissions:
  contents: read

jobs:
  generate_documentation:
    permissions:
      contents: write  # for JamesIves/github-pages-deploy-action to push changes in repo
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    runs-on: ubuntu-20.04
    concurrency: gen-docs
    steps:
      - uses: actions/checkout@v3
      - name: Setup cache
        uses: actions/cache@v3
        with:
          path: ~/SpacemanDMM
          key: ${{ runner.os }}-spacemandmm-${{ secrets.CACHE_PURGE_KEY }}
>>>>>>> d75ed0d4c1f195874792113784be98d2fafb211e
      - name: Install SpacemanDMM
        run: bash tools/ci/install_spaceman_dmm.sh dmdoc
      - name: Generate documentation
        run: |
          ~/dmdoc
          touch dmdoc/.nojekyll
<<<<<<< HEAD
          # echo codedocs.tgstation13.org > dmdoc/CNAME #Removes the CNAME redirect. We aren't tgstation, surprisingly.
=======
          echo codedocs.cev-eris.net > dmdoc/CNAME
>>>>>>> d75ed0d4c1f195874792113784be98d2fafb211e
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          BRANCH: gh-pages
          CLEAN: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SINGLE_COMMIT: true
          FOLDER: dmdoc
