name: Make changelogs

on:
  push:
    branches: [master]

jobs:
  MakeCL:
    runs-on: ubuntu-latest
    if: github.repository == 'Occulus-Server/Occulus-Eris' # Occulus Edit - We want this to run
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 25
      - name: Python setup
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Install depends
        run: |
          python -m pip install --upgrade pip
          pip install ruamel.yaml PyGithub
      - name: Make CL
        env:
          #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }
          GITHUB_TOKEN: ${{ secrets.CL_TOKEN }}    # Occulus Edit / Allows this to create changelog files
          GIT_EMAIL: "action@github.com"
          GIT_NAME: "Nestor Jr." 
        run: python tools/changelog/generate_cl.py
